services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - celery-network

  celery:
    build: .
    container_name: celery
    volumes:
      - .:/app
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - celery-network

networks:
  celery-network:
